---
# Customizable variables
operator_version: ""
registry_url: quay.io
repo_name: rh-nfv-int

# Internal variables
image_pull_policy: Always

catalog_name: nfv-example-cnf-catalog
catalog_image: "{{ registry_url }}/{{ repo_name }}/{{ catalog_name }}:{{ operator_version }}"

cnf_namespace: example-cnf
